# Generated by Django 4.1.2 on 2022-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0002_rename_hotel_main_img_hotel_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="img",
            field=models.ImageField(upload_to=""),
        ),
    ]
