# Generated by Django 4.1.3 on 2022-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0003_alter_hotel_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="img",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
